#!/bin/bash

sudo pacman -S vim neofetch steam musescore lutris keepass wget git zsh tmux cmus htop arc-gtk-theme
pamac build spotify

echo Configure Steam
mkdir ~/.steam/root/compatibilitytools.d
cd ~/Téléchargements
wget https://github.com/GloriousEggroll/proton-ge-custom/releases/download/5.4-GE-1/Proton-5.4-GE-1.tar.gz

tar xvzf Proton-5.4-GE-1.tar.gz
mv Proton-5.4-GE-1 ~/.steam/root/compatibilitytools.d/
cd ~

sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
chsh -s /bin/zsh

git clone https://github.com/LittleVaaty/dotfiles.git
sh ~/dotfiles/install_dotfile.sh
