export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"
ZSH_TMUX_AUTOSTART=true

plugins=(git tmux zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh


alias ll="ls -lah"
alias l="ls"
alias mkdir="mkdir -p"

alias v="nvim"

alias ls="lsd"
alias cat="bat"

export EDITOR=nvim

eval "$(atuin init zsh)"
eval "$(starship init zsh)"
